= Camunda HELM Charts
Doc Writer <paul.lungu@camunda.com>
v1.0, 2020-03-15
:toc:

== Goals
- Simple and understandable HELM example
- Help understand common configuration and architectural concepts
- Good documentation and example to assist in getting running quickly in Kubernetes
- *NOT* intended as a production ready configuration

NOTE: for example of installing on AWS EKS see link:docs/install-camunda-aws-eks.adoc[Install Camunda Platform on EKS]

== What is configured in this chart
- [x] Camunda BPM CE
- [x] Camunda BPM EE
- [x] Camunda License Install
- [x] Internal Load Balancer Service (for clients like Optimize)
- [x] External Ingress with sticky sessions
- [x] Postgres Database

== How does it work

IMPORTANT: The configs in this chart are preconfigured defaults and serve as a quick reference for understanding. *You may need to change and adjust things to suit your use-case, infra, architecture, etc ...*

- The HELM chart is an install descriptor to install Canunda on Kubernetes. HELM can do many things to help install and manage infra on Kubernetes.
- The primary configuration point is the values.yaml. It should allow you to get a basic Canunda configuration installed and running with little to no customizations.
- You still need to know how to debug on Kubernetes. See the https://kubernetes.io/docs/tasks/debug-application-cluster/debug-application/[Kubernetes Docs] for help.
- While this chart defines how Canunda is installed other components need to be installed in your Kubernetes cluster to make Canunda work. See <<steps-to-run, Setting up Infra>> to install the other components.
- You can find more on HELM here https://helm.sh/docs/intro/quickstart/[Helm Quickstart]

== Steps to run this HELM chart

==== Before you run
NOTE: These can be omitted if you run the basic HELM chart without the Postgres DB and only a single node in the cluster without a load balancer

====
*Step 0. <<install-helm, Install HELM and Kubernetes>>* if not already installed

*Step 1. <<install-ingress-controller, Install Ingress Contorller>> to configure the loadbalaner ingress controller*

*Step 2. <<configure-external-database, Configure PostgreSQL>> in the Kubernetes cluster*

*Step 3. <<configure-camunda, Configure Camunda>>*

*Step 4. <<run-camunda, Run Camunda>>*
====

== [[setup-infra]] Setup Infra and Architecture for Camunda

==== [[install-helm]] *Step 0:* Install HELM and Kubernetes
====
- You can find more on HELM here https://helm.sh/docs/intro/quickstart/[Helm Quickstart]
- https://kubernetes.io/docs/setup/[Kubernetes Getting Started]
- Try https://www.docker.com/products/docker-desktop[Docker Desktop] imo it's the quickest way to get started with Kubernetes

- Tested with HELM
** `version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.16"}`

- Tested with Kubernetes
** `Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/amd64"}`

** `Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:53:14Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}`

====

---
[[install-ingress-controller]]
=== *Step 1:* Configure Load Balancer with Sticky Sessions

==== Install Ingress Controller
====
IMPORTANT: Kuberneted does not come with an implementation of a LoadBalancer or a Reverse Proxy for Ingress. The Ingerss resource allows you to configure a Controller for your needs. It's important to understand what you need from an inrgess resource then you can choose the appropriate Controller to install. There are a variety of vendors.

*Tested with* https://kubernetes.github.io/ingress-nginx/deploy/#docker-for-mac

*Install the NGINX Ingress Controller*
----
kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v0.44.0/deploy/static/provider/cloud/deploy.yaml
----
====

---

==== Configure the Ingress Resource for nginx with sticky sessions
====
Update the values.yaml and configure the Ingress Resource to tell the LoadBalancer (the NGINX deployment that was installed above) to stick to one Camunda instance once the user is logged into the Camunda webapps.

*Defaults Below*
[source,yaml]
----
  ingress:
    enabled: true
    annotations: {
        nginx.ingress.kubernetes.io/ingress.class: nginx,
        nginx.ingress.kubernetes.io/affinity: "cookie",
        nginx.ingress.kubernetes.io/affinity-mode: "persistent",
        nginx.ingress.kubernetes.io/session-cookie-expires: "172800",
        nginx.ingress.kubernetes.io/session-cookie-max-age: "172800",
      }
      # see more config options https://kubernetes.github.io/ingress-nginx/examples/affinity/cookie/
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: camunda.127.0.0.1.nip.io
        paths: ["/"]
    tls: []
    #  - secretName: camunda-bpm-platform-tls
    #    hosts:
    #      - camunda-bpm-platform.local   - camunda-bpm-platform.local

----
====

---

===== *Increase the replica count of Camunda Nodes*
====

Update the values.yaml and increase the replica count so the load balancer will send requests to both nodes for a user that is not already logged in to Camunda webapps.

*Defaults Below*
[source,yaml]
----
general:
  debug: true
  replicaCount: 2
  nameOverride: ""
  fullnameOverride: ""
----
====

---

[[configure-external-database]]
=== *Step 2:* Configure an External Database

==== *Install PostgreSQL Database in the cluster*
====
----
helm install workflow-database --set postgresqlUsername=workflow,postgresqlPassword=workflow,postgresqlDatabase=workflow bitnami/postgresql
----
====
Based on: https://artifacthub.io/packages/helm/bitnami/postgresql

---

===== *Create Kubernetes Secret Resource for Postgresql*
====
----
kubectl create secret generic \
    workflow-database-credentials \
    --from-literal=DB_USERNAME=workflow \
    --from-literal=DB_PASSWORD=workflow
----
====

---

===== *Update the values.yaml with database configuration*
====

The `credentialsSecertName:` allows us to use a secret resource for DB credentials.

The `url:` uses the deployment name of the postgres resource. This is echoed in the notes after the install.

*Defaults Below*
[source,yaml]
----
database:
  # In case H2 database is used.
  internal:
    enabled: false
    diskSize: 1G
  # In case PostgreSQL or MySQL databases are used.
  external:
    enabled: true
    credentialsSecertName: "workflow-database-credentials"
    driver: "org.postgresql.Driver"
    url: "jdbc:postgresql://workflow-database-postgresql.default.svc.cluster.local:5432/workflow"
----

For more configuration options see https://github.com/camunda/docker-camunda-bpm-platform/blob/next/README.md
====

---
=== *Step 3:* Configure Camunda
==== Configure the version of Camunda
====
In this case the latest tomcat image is used.

Use the *tag* property to change the version.

See the https://hub.docker.com/r/camunda/camunda-bpm-platform/tags[Camunda Docker Tags] if you need a different version of Camunda.

*Run the Community Version*
[source,yaml]
----
image:
  repository: camunda/camunda-bpm-platform
  tag: tomcat-latest
  pullPolicy: IfNotPresent
  pullSecrets: []
----
---
*Run the Enterprise Version*

IMPORTANT: https://camunda.com/download/enterprise/[Get an enterprise trial to try Camunda EE]

[source,yaml]
----
image:
  repository: registry.camunda.cloud/cambpm-ee/camunda-bpm-platform-ee
  tag: latest
  pullPolicy: IfNotPresent
  pullSecrets:
  - name: camunda-reg-cred
----

---
NOTE: If issues arise with pulling the image the workaround is to manually pull the image.
Run the following commands

 docker login registry.camunda.cloud

 docker pull registry.camunda.cloud/optimize-ee/optimize:latest

---

*Configuring the pullSecrets*

TIP: see https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/[Configuring pull secrets kubernetes doc] and https://kubernetes.io/docs/tasks/configmap-secret/managing-secret-using-kubectl/[Managing Secrets] for more info

Install the secret and name it camunda-reg-cred

----
kubectl create secret docker-registry camunda-reg-cred --docker-server=registry.camunda.cloud --docker-username=<<user>> --docker-password=<<password>> --docker-email=<your-email>
----

TIP: You may need to deref special characters in your passwords i.e. --docker-password=mypassword\!isstrong

Check your secret
----
kubectl get secret camunda-reg-cred --output=yaml

kubectl get secret camunda-reg-cred --output="jsonpath={.data.\.dockerconfigjson}" | base64 --decode
----

====

---
=== *Step 4:* Run the Chart
====
**Runing the Chart** the following command to install the chart and apply the configurations to the Kubernetes cluster
----
helm install workflow-demo ./charts/camunda-bpm-platform/
----

**Change the Chart ** -- When you make changes run the following command to apply the changes to the cluster
----
helm upgrade workflow-demo ./charts/camunda-bpm-platform/
----

**Remove the Chart **  -- To remove the installation
----
helm uninstall workflow-demo
----

====

== Whats Next
- [x] Configuration for EE License
- [x] Configuration for Secrets Vault (HashiCorp, Spring Cloud Vault)
- [x] Configure common Camunda configs (Hisotry Level, Engine)
- [x] Configuration for Optimize
- [ ] Configure Cawemo on Premise
- [ ] Adding a Camunda process application
- [ ] Configuration for LDAP plugin
- [ ] Adding an Engine plugin
- [ ] Configuration for metrics
** [ ] with Prometheus
- [ ] Configuration for Custom Camunda Build
** with Spring-Boot
- [ ] Configuration for Logging
** [ ] Configuration for Log Drain
- [ ] Configuration for CI/CD
** [ ] Configuration for ARGO
** [ ] Configuration for TERRAFORM
- [ ] Configurations for SSO
** [ ] with Keycloak
- [ ] Configuration for GRAPHQL
- [ ] Configuration for HAZELCAST
- [ ] Configuration for Tracing
- [ ] Configure auto-scaling
- [ ] Configure Cloud Deployments (GKE, AWS, Azure)

== Based on Camunda Helm
vault server -dev -dev-root-token-id root -dev-listen-address 0.0.0.0:8200
image:https://img.shields.io/endpoint?url=https://artifacthub.io/badge/repository/camunda[link=https://artifacthub.io/packages/search?repo=camunda]

*More Info*

- https://artifacthub.io/packages/helm/camunda/camunda-bpm-platform
- https://kubernetes.github.io/ingress-nginx/deploy/#docker-for-mac
- https://helm.sh/docs/intro/quickstart/
- https://hub.docker.com/r/camunda/camunda-bpm-platform
- https://kubernetes.github.io/ingress-nginx/examples/affinity/cookie/
- https://github.com/camunda/camunda-helm
- https://github.com/camunda/docker-camunda-bpm-platform
- https://artifacthub.io/packages/helm/bitnami/postgresql

== Project state

NOTE: This project is in **alpha** phase.
